/* eslint-disable */
// WARNING: Do not edit this file
// https://app.easybase.io/#/projects

const ebconfig = {
  integration: 'project-490-M4OkCuAIXJA1dlfB6kJFL5OIwM8HLoSA',
  version: '2020-11-20',
};

export default ebconfig;
